title: "> blogfuscated_"
description: "obfuscatedgenerated's blog"
author: obfuscatedgenerated
url: https://blog.ollieg.codes

remote_theme: obfuscatedgenerated/startbootstrap-clean-blog-jekyll

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
paginate: 5
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-sitemap
